### ISSUE TITLE
Presenting DBIx::Class::ResultSet does not work correctly

### ISSUE THREAD

**Issue by brtastic** [khrt/Raisin#110]
The example from MusicApp with DBIx::Class does not work correctly.

```
my $artists = $schema->resultset('Artist');
 
present data => $artists, with => 'MusicApp::Entity::Artist';
present count => $artists->count;
```
This causes an error for empty resultsets and incorrect output for anything else.

The reason seem to be Raisin::Entity, line 148:
- the `->first` method may return a new object that will have the `->columns_info` method, but for empty resultsets it returns `undef`
- even for resultsets which have some rows and can have their columns info retrieved, the `->first` method has already moved the iterator to the next position, and every call to `->next` will move it even further. The count shown is not equal to the actual count of items returned. If the database has only one record, the result is:
```
{"data":[],"count":1}
```

**Comment by brtastic** [comment]
I'm not sure why doesn't this work, seen some previous discussion in issues where someone claimed it did actually work, but seems like there been no significant change to this in DBIx::Class recently, and no change in this Raisin code for the last 7 years.

To be precise, I did not run the MusicApp directly, but used its code for my own needs with PostgreSQL. The entities and models are a bit different, but the general way they're used is the same as in MusicApp.

**Comment by brtastic** [comment]
I was missing two things:
- no `use MyApp::Entity::SomeEntity` at the top of the file
- no `with => 'MyApp::Entity::SomeEntity'` (sort of)

So the behavior is very weird and needs to be patched / documented because looks like a bug at first glance:
- with `use` at the top but no `with`, I get an error described above
- same with no `use` at the top but having `with`
- only when both of them are present, the behavior is correct
- nothing was telling me that I'm doing something wrong, only after I've added `entity 'MyApp::Entity::SomeEntity';` to API description I was able to spot an issue (since it was telling me that I probably forgot to load the module)

**Comment by khrt** [comment]
Thanks for reporting! The bug was there from the very beginning and must be fixed now. 

The new version is released to CPAN as 0.92.

**Comment by brtastic** [comment]
@khrt Thank you, however I still don't think if the change you've introduced is enough, since the chain `$data->first->columns_info` is erroneous if there are no rows in the result (since it's pretty much `undef->columns_info` then and there seem to be no checks whether the ResultSet is empty). It would've fixed the non-visible first element in my case, but not the exception with no rows in the database.

**Comment by khrt** [comment]
@brtastic, right. I skipped that case, let me see what I can do to fix it.

**Comment by khrt** [comment]
Should be fixed now with the recent change.
